site_name: All Nooie Wiki
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  palette:
    scheme: default
nav:
  - Introduction: index.md
  - Game Vision:
    - Game Theme: game-vision/game-theme.md
    - Graphics Environment: game-vision/visual-appearance.md
  - Game Progress:
    - Main Character Mechanics: game-mechanics/main-character.md
