site_name: All Nooie Wiki
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  palette:
    scheme: default
nav:
  - Introduction: index.md
  - Engine:
    - Game Vision:
      - Game Theme: engine/game-vision/game-theme.md
      - Graphics Environment: engine/game-vision/visual-appearance.md
    - Game Progress:
      - Main Character Mechanics: engine/game-mechanics/main-character.md
