site_name: All Nooie Wiki
theme:
  name: readthedocs
  color_mode: auto
  user_color_mode_toggle: true
  palette:
    scheme: default
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
nav:
  - Introduction: index.md
  - Collectible Items:
    - Notes: collectibles/notes.md
    - Jiggies: collectibles/jiggies.md
    - Blue Eggs: collectibles/blue-eggs.md
    - Red Feathers: collectibles/red-feathers.md
    - Golden Feathers: collectibles/golden-feathers.md
    - Honeycombs: collectibles/honeycombs.md
    - Hollow Honeycombs: collectibles/hollow-honeycombs.md
